name: Deploy React Client

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SECRET_KEY }}
          script: |
            cd /var/www/valser.az
            git pull
            npm install
            npm run build
